# Generated by Django 3.0 on 2020-01-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200114_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/Users/kailu/Desktop/Sides/personal_website/projects/static/img'),
        ),
    ]
