# Generated by Django 3.0.7 on 2020-06-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200114_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/Users/kailu/Desktop/projects/UpdatedSite/projects/static/img'),
        ),
    ]
