# Generated by Django 3.0.7 on 2020-06-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200610_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
        migrations.AddField(
            model_name='project',
            name='previewDescription',
            field=models.CharField(default='preview', max_length=300),
        ),
    ]
