# Generated by Django 3.0 on 2020-01-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.FilePathField(path='/Users/kailu/Desktop/Sides/personal_website/about/static/img'),
        ),
    ]
