# Generated by Django 3.0.7 on 2020-06-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200114_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.FilePathField(path='/Users/kailu/Desktop/projects/UpdatedSite/about/static/img'),
        ),
    ]
