# Generated by Django 3.0.7 on 2020-06-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20200609_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
