# Generated by Django 3.0.7 on 2020-06-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20200610_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
